---
apiVersion: v1
kind: Service
metadata:
  name: cgroup-burst
  namespace: cgroup-burst
  labels:
    app: cgroup-burst
spec:
  selector:
    app: cgroup-burst
  ports:
  - name: metrics
    port: 2112
    targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cgroup-burst
  namespace: cgroup-burst
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: cgroup-burst
  endpoints:
    # app own metrics
  - port: metrics
    # metrics for related containers
  - port: metrics
    path: /container_metrics
    honorLabels: true
    honorTimestamps: true
    relabelings:
    - action: labeldrop
      regex: container|endpoint|namespace|pod|service
    metricRelabelings:
    - action: labeldrop
      # for some reason, relabelings can't drop instance label
      regex: instance
