---
apiVersion: v1
kind: Service
metadata:
  name: cgroup-burst
  namespace: cgroup-burst
  labels:
    app: cgroup-burst
spec:
  selector:
    app: cgroup-burst
  ports:
  - name: metrics
    port: 2112
    targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cgroup-burst
  namespace: cgroup-burst
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: cgroup-burst
  endpoints:
    # app own metrics
  - port: metrics
    scheme: http
    relabelings:
    - targetLabel: instance # turn instance from ip:port into node name
      sourceLabels: [ __meta_kubernetes_endpoint_node_name ]
    # metrics for related containers
  - port: metrics
    scheme: http
    path: /container_metrics
    honorLabels: true
    honorTimestamps: true
    relabelings:
      # metrics on this endpoint are not related to the app instance,
      # so we need to drop all automatic labels from service discovery
    - action: labeldrop
      regex: container|endpoint|namespace|pod|service
    metricRelabelings:
    - action: labeldrop
      # for some reason, relabelings can't drop instance label
      regex: instance
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alert-cgroup-burst
spec:
  groups:
  - name: cgroup-burst
    rules:
    - alert: CgroupBurstEventErrors
      annotations:
        description: >-
          {{ $labels.instance }}:
          {{ $value | humanize }}
        summary: Got more than 2 error events in 1 minute
      expr: |-
        increase(cgroup_burst_k8s_watch_events_total{type="error"}[1m]) > 2
      for: 10m
      labels:
        severity: warning
    - alert: CgroupBurstMissingBookmarks
      annotations:
        description: >-
          {{ $labels.instance }}:
          {{ $value | humanize }}
        summary: Received less than 3 bookmark events in 5 minutes
      expr: |-
        increase(cgroup_burst_k8s_watch_events_total{type="bookmark"}[5m]) < 3
      for: 10m
      labels:
        severity: warning
    - alert: CgroupBurstTooManyWatches
      annotations:
        description: >-
          {{ $labels.instance }}:
          {{ $value | humanize }}
        summary: Created more than 3 watches in 1 minute
      expr: |-
        increase(cgroup_burst_k8s_watch_streams_total[1m]) > 3
      for: 1m
      labels:
        severity: warning
    - alert: CgroupBurstPodsWithoutAnnotation
      annotations:
        description: >-
          {{ $labels.instance }}:
          {{ $value | humanize }}
        summary: Some pods with matching label don't specify burst annotation
      expr: |-
        cgroup_burst_pod_annotations_missing_total != 0
      for: 1m
      labels:
        severity: warning
    - alert: CgroupBurstPodsWithoutAnnotation
      annotations:
        description: >-
          {{ $labels.instance }}:
          {{ $value | humanize }}
        summary: Some pods' annotations specify containers that don't exist
      expr: |-
        cgroup_burst_pod_annotations_unused_total != 0
      for: 1m
      labels:
        severity: warning
